# Example of Server configuration file
# To run the server using the settings defined
# in this configuration file, use the following commmand: 
#
# $ python -m mdwiki server --config=./example.toml
#
[server]
port        = 8000                             # TCP port to be listened, default 8080
#host       = "127.0.0.1"                      # Default (Localhost)
host        = "0.0.0.0"                        # Listen to all network interfaces
debug       = true                             # Enable or Disable Debug 
random-ssl  = false                            # Enable random self-signed certificate 
                                               # for SSL/TLS connection 
login       = true                             # Enable or disable login 
username    = "myusername"                     # Username 
password    = "mypassword"                     # Password
wikipath    = "./pages"                        # Path to *.md files folder  
